### ISSUE TITLE
Feature Request - Add Upload To Put.io

### ISSUE THREAD

**Issue by krash1220** [posborne/putio-sync#22]
I would really like to see an option to have putio-sync watch a particular folder for torrents and upload them to a put.io account and then download them like it does now.

**Comment by posborne** [comment]
Here's what I think could fit the bill:

    $ putiosync -w D:\Torrents\Unprocessed D:\Downloads

Where the `-w` option is a directory to "watch" for new torrent files.  When a new torrent file is added to that directory, the daemon would automatically add it to put.io and move the torrent file to a processed directory (or maybe tag it as processed in its database; input here welcome).  All you would need to do is put torrents in that folder (or have another app put them in that folder) and they would be added to put.io automatically.

**Comment by posborne** [comment]
There is now directory watch and basic tranmission RPC API support

**Comment by krash1220** [comment]
Is this suppose to be working now or it's just added but not released?

**Comment by posborne** [comment]
It is in master but I have not pushed a new release to pypi (so it can be pip installed).

**Comment by krash1220** [comment]
Well, I've tried pip install three times but I didn't know what to change the command to instead of putiosync D:\Downloads and so I did the putiosync -h but that didn't tell me what the new command was either. I tried putiosync -w D:\Torrents\Unprocessed D:\Downloads but it says that's not correct. So how do I get it to watch a certain folder?

**Comment by dannydan412** [comment]
How do I get the latest version with this feature? If i just clone the dir from github, how do I install it?

**Comment by okmatt** [comment]
@dannydan412 There's more than one way but this is how I do it on a Mac:

1. Download the zip.
2. Use Terminal to cd to the unzipped folder "cd ~/Downloads/putio-sync-master"
3. Install it "sudo python setup.py install"

If you have a previous version you will need to "sudo pip uninstall putiosync"

**Comment by dannydan412** [comment]
Thanks @okmatt!
I'm getting the following error when running it though:
2016-12-18 01:48:58,151 | putiosync    | WARNING  | Starting main application
2016-12-18 01:48:58,565 | putiosync.webif.webif | ERROR    | Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "build\bdist.win32\egg\putiosync\webif\webif.py", line 145, in _view_active
    return render_template("active.html")
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Python27\lib\site-packages\jinja2-2.8-py2.7.egg\jinja2\environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python27\lib\site-packages\jinja2-2.8-py2.7.egg\jinja2\environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Python27\lib\site-packages\jinja2-2.8-py2.7.egg\jinja2\environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: active.html

Any ideas?

**Comment by nuclear-foss** [comment]
I'm not a developer of putio-sync and I don't use it but the code looks good ;)

What OS are you using?
What terminal app?
What are the environment variables?
What's the current working directory when you launch the app?

You could try to explicitly define the relevant paths.

Add this to putio-sync/webif/webif.py:

```py
self.app.root_path = os.path.dirname(os.path.abspath(__file__))
```

Maybe use instance_path instead as mentioned [here](https://stackoverflow.com/questions/36649703/get-root-path-of-flask-application).

You would add the code [here](https://github.com/posborne/putio-sync/blob/master/putiosync/webif/webif.py#L99).

And you might have to add `import os` to the top of the same file.

Hope that helps!

**Comment by nuclear-foss** [comment]
Oh... Your using _Windows_? Thats a shame. :worried:
Which means your probably using the _Windows command interperter_ aka _command prompt_.
I should have realized that from the path at first glance.

Anyways... I actually don't want to help you because of that. :laughing:
