### ISSUE TITLE
Hard dependency on requests=2.2.0 triggers SSL issues

### ISSUE THREAD

**Issue by alasdaircr** [posborne/putio-sync#44]
python2.7
debian 8.0
raspberrypi

There's an issues with `requests` around SSLv3 (I'm no python dev so can't debug) which is solved by upgrading to a more recent version. However this package (including when installing via git) requires version 2.2.0 explicitly.

If possible could you remove that dependency. I read that version 2.6.0 works fine.

```
Traceback (most recent call last):
  File "/usr/local/bin/putiosync", line 9, in <module>
    load_entry_point('putiosync==0.2.3', 'console_scripts', 'putiosync')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/putiosync/frontend.py", line 6, in <module>
    import putio
  File "/usr/local/lib/python2.7/dist-packages/putio.py", line 9, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 43, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
```

**Comment by alasdaircr** [comment]
FYI: I just edited `requirements.txt` changed `requests==2.6.0` reinstalled and it's working
